name: Unzip File in Repository

on:
  workflow_dispatch:  # Allows you to manually run the workflow
  push:
    branches:
      - master  # Trigger when changes are pushed to the 'master' branch (you can replace it with your branch name)

jobs:
  unzip:
    runs-on: ubuntu-latest  # Runs on an Ubuntu VM

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Unzip New-Lakshmi.zip into the root of the repository
      - name: Unzip New-Lakshmi.zip
        run: |
          # Check if the file exists
          if [ ! -f "New-Lakshmi.zip" ]; then
            echo "Error: New-Lakshmi.zip not found in the repository."
            exit 1
          fi

          # Create a temporary folder for unzipping
          mkdir -p temp_unzip
          
          # Unzip the file into the temporary folder
          unzip -o New-Lakshmi.zip -d temp_unzip

          # Move the extracted files into the root folder
          rsync -av --delete temp_unzip/ ./ 

          # Clean up the temporary folder
          rm -rf temp_unzip
          
      # Step 3: Commit and Push Unzipped Files to the repository (if needed)
      - name: Commit and Push Unzipped Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub-provided token for authentication
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Unzipped New-Lakshmi.zip into root" || echo "No changes to commit"
          git push origin master  # Push changes to the 'master' branch
