name: Unzip File and Extract to Root

on:
  workflow_dispatch:  # Manually trigger the workflow
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  unzip:
    runs-on: ubuntu-latest  # Use Ubuntu for this workflow

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Verify ZIP file exists in root directory
      - name: Verify ZIP file exists
        run: |
          if [ ! -f "New-Lakshmi.zip" ]; then
            echo "Error: New-Lakshmi.zip not found."
            exit 1
          fi

      # Step 3: List files in the repository (for debugging)
      - name: List files in the repository before extraction
        run: ls -alh

      # Step 4: Unzip New-Lakshmi.zip to root
      - name: Unzip New-Lakshmi.zip to root directory
        run: |
          mkdir -p temp_unzip
          unzip -o New-Lakshmi.zip -d temp_unzip  # Extract to temp folder
          
          # Remove backslashes from paths and place the files in the root
          rsync -av --remove-source-files temp_unzip/ ./  # Move files from temp_unzip to the root
          
          # Clean up the temporary folder
          rm -rf temp_unzip

      # Step 5: List files in the repository after extraction (for debugging)
      - name: List files in the repository after extraction
        run: ls -alh

      # Step 6: Commit and push changes (if needed)
      - name: Commit and Push Unzipped Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Unzipped New-Lakshmi.zip to root" || echo "No changes to commit"
          git push origin main
