name: Unzip File and Extract to Root

# Trigger the workflow manually or on push to a specific branch
on:
  workflow_dispatch:  # Manually trigger the workflow
  push:
    branches:
      - main  # Change 'main' to your branch name if different

jobs:
  unzip:
    runs-on: ubuntu-latest  # This will run the job on an Ubuntu machine

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # We make sure we are pulling the correct branch
          ref: main  # Ensure it’s the branch you want to work with (e.g., main or master)

      # Step 2: Verify the ZIP file exists
      - name: Verify ZIP file exists
        run: |
          # Ensure New-Lakshmi.zip exists in the root directory
          if [ ! -f "New-Lakshmi.zip" ]; then
            echo "Error: New-Lakshmi.zip not found in the repository."
            exit 1
          fi

      # Step 3: Unzip New-Lakshmi.zip to root directory
      - name: Unzip New-Lakshmi.zip to root directory
        run: |
          # Create a temporary directory to unzip the contents
          mkdir -p temp_unzip
          
          # Unzip New-Lakshmi.zip into the temporary folder
          unzip -o New-Lakshmi.zip -d temp_unzip
          
          # Move all files and directories from temp_unzip to the root of the repository
          rsync -av --delete temp_unzip/ ./  # Overwrites existing files in the root directory
          
          # Clean up the temporary folder
          rm -rf temp_unzip
          
      # Step 4: Commit and Push Changes (if any changes are made)
      - name: Commit and Push Unzipped Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to authenticate the push
        run: |
          # Configure GitHub Actions to commit changes
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Add all files that were unzipped and are now in the root directory
          git add .
          
          # Commit the changes if there were any changes after unzipping
          git commit -m "Unzipped New-Lakshmi.zip to root" || echo "No changes to commit"
          
          # Push the changes to the repository (e.g., to the main branch)
          git push origin main  # Change this if you are working with a different branch
