name: Unzip File in Repository

on:
  workflow_dispatch: # Allows you to manually run the workflow
  push: # Runs automatically when you push changes to the repository
    branches:
      - main # Replace 'main' with your branch name if different

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Verify ZIP file exists
      - name: Verify ZIP file exists
        run: |
          if [ ! -f "New-Lakshmi.zip" ]; then
            echo "Error: New-Lakshmi.zip not found in the repository root."
            exit 1
          fi

      # Step 3: Unzip the file into the root folder
      - name: Unzip New-Lakshmi.zip into the root
        run: |
          mkdir -p temp_unzip
          unzip -o New-Lakshmi.zip -d temp_unzip
          mv temp_unzip/* .
          ls -la

      # Step 4: Commit and Push Unzipped Files
      - name: Commit and Push Unzipped Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub-provided token for authentication
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Unzipped New-Lakshmi.zip to root"
          git push origin main
