name: Unzip File in Repository

on:
  workflow_dispatch: # Allows you to manually run the workflow
  push: # Runs automatically when you push changes to the repository
    branches:
      - main # Replace 'main' with your branch name if different

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Unzip the file into the root folder
      - name: Unzip New-Lakshmi.zip into the root
        run: |
          unzip -o New-Lakshmi.zip -d . # Extracts directly into the root directory
          ls -l # Lists the extracted files for confirmation

      # Step 3: Commit and push the unzipped files to the repository
      - name: Commit and Push Unzipped Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub-provided token for authentication
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Unzipped New-Lakshmi.zip to root"
          git push origin main
