name: Unzip File in Repository

on:
  workflow_dispatch:  # Manually trigger the workflow
  push:
    branches:
      - main  # Runs on changes pushed to the main branch

jobs:
  unzip:
    runs-on: ubuntu-latest  # Use an Ubuntu virtual machine for the workflow

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Verify the ZIP file exists
      - name: Verify ZIP file exists
        run: |
          if [ ! -f "New-Lakshmi.zip" ]; then
            echo "Error: New-Lakshmi.zip not found in the repository root."
            exit 1
          fi

      # Step 3: Unzip the ZIP file into the repository root
      - name: Unzip New-Lakshmi.zip to root
        run: |
          mkdir -p temp_unzip  # Create a temporary directory
          unzip -o New-Lakshmi.zip -d temp_unzip  # Extract to the temp directory
          rsync -av temp_unzip/ ./  # Move files from temp_unzip to the root
          rm -rf temp_unzip  # Clean up temporary files

      # Step 4: Commit and Push Unzipped Files (if changes exist)
      - name: Commit and Push Unzipped Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Unzipped New-Lakshmi.zip to root" || echo "No changes to commit"
          git push origin main
